config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/health', to: 'health#liveness'
  get '/health/liveness', to: 'health#liveness'
  get '/health/readiness', to: 'health#readiness'

  get '/welcome', to: 'welcome#index'

  get '/profile', to: 'profile#index'
  get '/profile/change_password', to: 'profile#change_password', as: 'change_password'

  get '/auth/auth0/callback' => 'auth0#callback', as: 'auth0_callback'
  get '/auth/failure' => 'auth0#failure', as: 'auth0_failure'
  get '/auth/logout' => 'auth0#logout', as: 'auth0_logout'

  resources :recipes do
    collection do
      get 'filter_by_tag/:tagid' => :filter_by_tag, as: 'filter_by_tag'
      get 'search(/:term)' => :search, as: 'search'
      get 'new_magic' => :new_magic
    end
    member do
      put 'favorite'
    end
    resources :recipe_images, only: [:new, :create] do
      collection do
        get 'delete_select'
        put 'delete'
      end
    end
  end
  resources :tags do
    collection do
      get 'search(/:term)' => :search, as: 'search'
    end
  end

  resources :ocr, only: [] do
    collection do
      post 'scan'
      post 'select_recipe'
    end
    member do
      post 'cleanup_with_gpt'
      get 'select_image_for_reparse'
      post 'reparse_image'
      get 'select_recipe', to: 'ocr#show_recipe_selection', as: 'select_recipe'
    end
  end

  resources :ocr_debug, only: [:index, :show] do
    collection do
      post 'upload'
    end
  end

  root to: 'recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :tags, after_remove: :after_remove_tag
  has_many_attached :recipe_images
  has_rich_text :instructions
  has_rich_text :ingredients

  validates :name, presence: true

  after_save :update_tags_count
  before_destroy :update_tags_count

  paginates_per 15

  scope :order_by_name, -> { order(Recipe.arel_table[:name].lower, :id) }

  def tag_names
    # Get all related Tags as comma-separated list
    tag_list = []
    tags.each do |tag|
      tag_list << tag.name
    end
    tag_list.join(', ')
  end

  def tag_names=(names)
    # Split comma-separated list names
    tag_names_new = names.split(',').map{ |n| n.strip }.select{ |n| ! n.empty? }
    tag_names_old = self.tags.map{ |t| t.name }
    tags_to_add = tag_names_new - tag_names_old
    tags_to_remove = tag_names_old - tag_names_new
    logger.debug "tags_to_add #{tags_to_add} / tags_to_remove #{tags_to_remove}"

    # removed tags
    tags_to_remove.each do |tag_name|
      tag = Tag.find_by(name: tag_name)
      self.tags.delete(tag)
    end

    # added tags
    tags_to_add.each do |name|
      tag = Tag.find_or_create_by(name: name)
      logger.info tag
      self.tags << tag
    end
  end

  def add_images=(images)
    images.each do |image|
      self.recipe_images.attach(image)
    end
  end

  def update_tags_count
    tags.each do |tag|
      tag.recipes_count = tag.recipes.count
      tag.save
    end
  end

  def after_remove_tag(tag)
    logger.debug "after_remove_tag #{tag.name}}"
    tag.recipes_count = tag.recipes.count
    tag.save
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include Secured

  def index
    @recipes = Recipe

    if params[:latest_first]
      @recipes = @recipes.order(created_at: :desc)
    elsif params[:rating]
      @recipes = @recipes.where(rating: params[:rating]).order(name: :asc)
    elsif params[:rating_null]
      @recipes = @recipes.where(rating: nil).order(name: :asc)
    else
      @recipes = @recipes.order(favorite: :desc).order(name: :asc)
    end

    @recipes = @recipes.page params[:page]
  end

  def filter_by_tag
    @recipes = Recipe.joins(:tags).where(tags: { id: params[:tagid] }).page params[:page]
    render 'index'
  end

  def search
    logger.debug "Search recipe for #{params[:term]}"
    if params[:term].nil?
      @recipes = Recipe.all.order_by_name
    else
      name_q = Recipe.arel_table[:name]
      @recipes = Recipe.where(name_q.matches("%#{params[:term]}%"))
    end

    @recipes = @recipes.page params[:page]

    respond_to do |format|
      if params[:full].nil?
        format.html { render partial: 'list' }
      else
        format.html { render 'index' }
      end
    end
  end

  def new
    @recipe = Recipe.new
    @ocrresult = nil
    @suggested_tags = nil
    populate_from_ocr_data(@recipe)
  end

  def new_magic
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = session[:userinfo]['id']

    if (params[:ocrresult_id].present?)
      ocrresult = OcrResult.find_by(id: params[:ocrresult_id])
      if ocrresult.present?
        @recipe.recipe_images.attach(ocrresult.image.blob) if ocrresult.image.attached?
      end
    end

    unless @recipe.valid?
      flash.now[:error] = @recipe.errors.messages.map{ |k,v|
        v
      }.join(',')
      render :new and return
    end

    @recipe.save

    redirect_to action: :show, id: @recipe.id
  end

  def show
    @recipe = Recipe.find(params[:id])
    @page_title = @recipe.name

    respond_to do |format|
      format.html
      format.json {
        render json: @recipe.as_json(
          only: [:id, :name, :duration, :source, :rating, :ocr_text]
        )
      }
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @page_title = @recipe.name
    @ocrresult = nil
    @suggested_tags = nil
    populate_from_ocr_data(@recipe)
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    recipe.save

    respond_to do |format|
      format.html { redirect_to action: :show, id: recipe }
      format.json { render json: { success: true, message: 'Recipe updated successfully' } }
    end
  end

  def favorite
    recipe = Recipe.find(params[:id])
    recipe.favorite = !recipe.favorite
    recipe.save
    render json: { redirect_url: recipe_path(recipe.id) }
  end

  def reparse_image
    @recipe = Recipe.find(params[:id])
    attachment_id = params[:attachment_id]

    begin
      # Find the selected image attachment
      attachment = @recipe.recipe_images.find(attachment_id)

      # Download the image blob and get content type
      blob = attachment.blob
      image_file = blob.download
      content_type = blob.content_type

      # Create a temporary file for the OpenAI service
      temp_file = Tempfile.new(['recipe_image', File.extname(blob.filename.to_s)])
      temp_file.binmode
      temp_file.write(image_file)
      temp_file.rewind

      # Call OpenAI service to parse the image
      openai = OpenaiService.new
      magic_data_json = openai.ocr(temp_file, content_type)

      # Save OCR result to database
      ocrresult = OcrResult.create(result: magic_data_json.to_s)
      ocrresult.image.attach(blob)
      ocrresult.save
      flash[:ocr_data] = ocrresult.id

      logger.debug "Reparse OCR data id stored in flash: #{flash[:ocr_data]}"

      redirect_to edit_recipe_path(@recipe)
    rescue JSON::ParserError => e
      logger.error "Reparse JSON parse error: #{e.message}"
      flash[:error] = I18n.t('ocr.errors.parse_failed')
      redirect_to recipe_path(@recipe)
    rescue => e
      logger.error "Reparse error: #{e.message}"
      flash[:error] = I18n.t('ocr.errors.processing_failed')
      redirect_to recipe_path(@recipe)
    ensure
      temp_file&.close
      temp_file&.unlink
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy()

    render json: { redirect_url: recipes_path }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :instructions, :duration, :tag_names, :source, :rating, :ocr_text)
  end

  def populate_from_ocr_data(recipe)
    # Check for OCR data in session and pre-populate
    logger.debug "OCR data in flash: #{flash[:ocr_data]}"
    return unless flash[:ocr_data].present?

    ocr_data_id = flash[:ocr_data]
    recipe_index = flash[:recipe_index] || 0
    @ocrresult = OcrResult.find_by(id: ocr_data_id)
    return unless @ocrresult.present?

    parsed_recipes = JSON.parse(@ocrresult.result)

    # Validate recipe_index bounds
    unless recipe_index >= 0 && recipe_index < parsed_recipes.length
      logger.error "Invalid recipe index: #{recipe_index} for #{parsed_recipes.length} recipes"
      flash.now[:error] = I18n.t('ocr.errors.invalid_recipe_index')
      return
    end

    ocr_data = parsed_recipes[recipe_index]
    recipe.name = ocr_data['title'] if ocr_data['title'].present?
    recipe.ingredients = format_ingredients_as_html(ocr_data['ingredients']) if ocr_data['ingredients'].present?
    recipe.instructions = format_steps_as_html(ocr_data['steps']) if ocr_data['steps'].present?

    # Extract suggested tags from OCR data
    if ocr_data['tags'].present? && ocr_data['tags'].is_a?(Array)
      tags = ocr_data['tags'].reject { |tag| tag == '[not found]' || tag.blank? }
      @suggested_tags = tags if tags.any?
    end

    flash.now[:warning] = I18n.t('ocr.warnings.ai_generated_data')
  end

  def format_ingredients_as_html(ingredients)
    return '' if ingredients.blank?

    items = ingredients.map { |item| "<li>#{ERB::Util.html_escape(item)}</li>" }.join
    "<ul>#{items}</ul>"
  end

  def format_steps_as_html(steps)
    return '' if steps.blank?

    items = steps.map { |step| "<li>#{ERB::Util.html_escape(step)}</li>" }.join
    "<ol>#{items}</ol>"
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def with_url_links(string)
    md = %r{https?:\/\/[A-Za-z0-9\-\._~:\/\?\#%@!$&'\(\)\+,;\=`\.]+}.match(string)
    return string if md.nil?
    url = md[0]
    front = string[0...md.begin(0)]
    back = string[md.end(0)...string.size]
    "#{front}<a href=\"#{url}\" target=\"_blank\">#{url}</a>#{back}".html_safe
  end

end

app/views/recipes/_form.html.erb
<div class="recipe noSubmitOnEnter mt-4" data-controller="recipeform" data-recipeform-url="<%= search_tags_path(term: 'term', format: :json) %>">
  <%= form_for @recipe do |f| %>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :name %>
      </div>
      <div>
        <%= f.text_field :name, placeholder: t('recipes.form.placeholder.name') %>
      </div>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :ingredients %>
      </div>
      <div>
        <%= f.rich_text_area :ingredients, placeholder: t('recipes.form.placeholder.ingredients') %>
      </div>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :instructions %>
      </div>
      <div>
        <%= f.rich_text_area :instructions, placeholder: t('recipes.form.placeholder.instructions') %>
      </div>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :duration %>
      </div>
      <div>
        <%= f.number_field :duration, placeholder: t('recipes.form.placeholder.duration'), autocomplete: 'off' %>
      </div>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :rating %>
      </div>
      <div>
        <%= f.hidden_field :rating, 'data-recipeform-target': 'rating' %>
        <% 5.times do |i| %>
          <% cls = if !@recipe.rating.nil? && i < @recipe.rating then 'fas' else 'far' end  %>
          <i class="<%= cls %> fa-star" 
              data-recipeform-target="rating-<%= i+1 %>"
              data-action="click->recipeform#setrating"
              data-recipeform-rating-param="<%= i+1 %>"></i>
        <% end %>
      </div>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :tags %>
      </div>
      <div>
        <%= f.text_field :tag_names, placeholder: t('recipes.form.placeholder.tags'), 'data-action': 'keyup->recipeform#findtags', 'data-recipeform-target': 'tags', autocomplete: 'off'  %>
      </div>
      <div data-recipeform-target="tagsSuggestion" class="tagsSuggestion">
      </div>
      <% if defined?(@suggested_tags) && @suggested_tags.present? %>
        <div class="mt-2">
          <div class="text-sm text-gray-600 mb-1"><%= t('recipes.form.ai_suggested_tags') %></div>
          <div class="flex flex-wrap gap-2">
            <% @suggested_tags.each do |tag| %>
              <button type="button"
                      class="px-3 py-1 bg-blue-100 hover:bg-blue-200 text-blue-800 rounded-full text-sm cursor-pointer transition-all duration-200 ai-suggested-tag"
                      data-action="click->recipeform#addSuggestedTag"
                      data-tag-value="<%= tag %>">
                <%= tag %>
              </button>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <div class="mb-2">
        <%= f.label :source %>
      </div>
      <div>
        <%= f.text_field :source, placeholder: t('recipes.form.placeholder.source'), autocomplete: 'off' %>
      </div>
    </div>
    <%= hidden_field_tag :ocrresult_id, @ocrresult.id if @ocrresult.present? %>
    <div class="mb-4">
      <div class="flex gap-2">
        <%= f.button t('action.save'), class: 'button' %>
        <% if @recipe.persisted? %>
          <%= link_to t('action.cancel'), recipe_path(@recipe), class: 'button' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/_list.html.erb
<ul class="list-none ps-0 md:ps-4">
  <% @recipes.each{ |r| %>
    <li class="py-2">
      <a class="nocolor" href="<%= recipe_path(r) %>"><%= r.name %></a>
      <% (r.rating || 0).times do |i| %>
        <i class="fas fa-star"></i>
      <% end %>
      <% if r.favorite %> 
        <i class="fas fa-heart"></i>
      <% end %>
    </li>
  <% } %>
</ul>

<%= paginate @recipes, window: 2, params: { full: true } %>

app/views/recipes/edit.html.erb
<div>
  <span class="heading_1">
    <%=t 'recipes.edit' %>
  </span>
</div>

<%= render partial: 'form' %>

app/views/recipes/index.html.erb
<div data-controller="search" data-search-url="<%= search_recipes_path %>">
  <p class="input_has_icons_left">
    <%= text_field_tag :search, params[:term], class: '', placeholder: t('action.search'), autocomplete: 'off',
        'data-action': 'keyup->search#search', 
        'data-search-target': 'term' %>
    <i class="fas fa-search"></i>
  </p>
  <div class="recipes" data-search-target="list">
    <%= render partial: 'list' %>
  </div>
  <div class="mt-4 pb-4 rating-filters">
    <a href="/"><%= t('recipes.show.alphabetically')%></a> |
    <a href="/?latest_first=true"><%= t('recipes.show.bydate') %></a> |
    <a href="/?rating=5"><i class="fa-solid fa-5"></i>&nbsp;<i class="fa-solid fa-star"></i></i></a> |
    <a href="/?rating=4"><i class="fa-solid fa-4"></i>&nbsp;<i class="fa-solid fa-star"></i></i></a> | 
    <a href="/?rating=3"><i class="fa-solid fa-3"></i>&nbsp;<i class="fa-solid fa-star"></i></i></a> |
    <a href="/?rating=2"><i class="fa-solid fa-2"></i>&nbsp;<i class="fa-solid fa-star"></i></i></a> |
    <a href="/?rating=1"><i class="fa-solid fa-1"></i>&nbsp;<i class="fa-solid fa-star"></i></i></a> | 
    <a href="/?rating_null=true"><i class="fa-solid fa-0"></i>&nbsp;<i class="fa-regular fa-star"></i></i></a>
  </div>
</div>

app/views/recipes/new.html.erb
<div>
  <span class="heading_1"><%=t 'recipes.new' %></span>
</div>

<%= render partial: 'form' %>

<% if @ocrresult&.image&.attached? %>
  <div class="mt-4">
    <span class="heading_2"><%= t('ocr.source_image') %>:</span>
    <div class="mt-2">
      <%= image_tag @ocrresult.image.variant(resize_to_fit: [400,400]), 
        class: "w-full h-48 object-cover rounded-lg shadow-md",
        loading: "lazy",
        alt: "Recipe image" %>
    </div>
  </div>
<% end %>

app/views/recipes/new_magic.html.erb
<div>
  <span class="heading_1"><%=t 'recipes.new_magic' %></span>
</div>

<div class="mb-4 mt-4">
  <label class="text-gray-700 font-semibold heading_2" for="ai_method_select">
    <%= t 'ocr.ai_method.label' %>
  </label>
  <select id="ai_method_select" 
          name="ai_method" 
          class="block w-full md:w-1/2 mt-2 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
    <option value="mistral_openai" selected><%= t 'ocr.ai_method.mistral_openai' %></option>
    <option value="openai_direct"><%= t 'ocr.ai_method.openai_direct' %></option>
  </select>
</div>

<%= render 'shared/dropzone', url: scan_ocr_index_path %>

app/views/recipes/show.html.erb
<div
    data-controller="recipe" 
    data-recipe-id="<%= @recipe.id %>" 
    data-recipe-url="<%= recipe_path(@recipe, :format => :json) %>" 
    data-recipe-favorite-url="<%= favorite_recipe_path(@recipe, :format => :json) %>" 
    data-recipe-editstate="false">
  <div>
    <span class="heading_1">
      <%= @recipe.name %>
      <% if @recipe.favorite %> 
        <i class="fas fa-heart is-size-5 text-primary"></i>
      <% end %>
    </span>
  </div>
  <div class="rating mt-2">
    <% 5.times do |i| %>
      <% if !@recipe.rating.nil? && i < @recipe.rating %>
        <i class="fas fa-star"></i>
      <% else %>
        <i class="far fa-star"></i>
      <% end %>
    <% end %>
    
  </div>
  <div class="ingredients mt-4">
    <p>
      <span class="heading_2"><%= t('recipes.ingredients') %></span>
    </p>
    <div class="prose mt-4">
      <%= @recipe.ingredients %>
    </div>
  </div>
  <div class="instructions mt-4">
    <p>
      <span class="heading_2">
        <%= t('recipes.instructions') %>
        <% if @recipe.duration %>
          <span class="subheading"><%=t 'recipes.show.duration' %>: <%= @recipe.duration %> <%=t 'recipes.show.durationunit' %></span>
        <% end %>
      </span>
    </p>
    <div class="content prose mt-4">
      <%= @recipe.instructions %>
    </div>
  </div>
  <% unless @recipe.source.nil? || @recipe.source.empty? %>
    <div class="recipe_source mt-4">
      <p><span class="heading_2"><%= t('recipes.show.source') %>:</span> <%= with_url_links @recipe.source %></p>
    </div>
  <% end %>
  <% unless @recipe.tags.empty? %>
    <div class="recipe_tags mt-4">
      <span class="heading_2 mr-2"><%=t 'recipes.show.tags' %>:</span>
      <% @recipe.tags.each{ |t| %>
        <%= render :partial => 'shared/tag', :locals => { tag: t } %>
      <% } %>
    </div>
  <% end %>

  <% if @recipe.recipe_images.count > 0 %>
    <div class="mb-6 mt-4" data-controller="lightbox">
      <p><span class="heading_2">Recipe Images:</span></p>
      
      <!-- Image Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
        <% @recipe.recipe_images.each_with_index do |image, index| %>
          <%= image_tag image.variant(resize_to_fit: [400,400]), 
              class: "w-full h-48 object-cover rounded-lg shadow-md cursor-pointer hover:shadow-lg transition-shadow duration-200 hover:scale-105 transform transition-transform",
              data: { 
                lightbox_target: "image",
                action: "click->lightbox#openLightbox",
                caption: "Recipe image #{index + 1}",
                full_url: url_for(image.variant(resize_to_fit: [800,2400])),
                original_url: url_for(image)
              },
              loading: "lazy",
              alt: "Recipe image #{index + 1}" %>
        <% end %>
      </div>

      <!-- Lightbox Modal -->
      <div class="lightbox-modal invisible" 
           data-lightbox-target="modal"
           data-action="click->lightbox#handleBackdropClick">
        
        <!-- Close Button -->
        <button class="lightbox-close" 
                data-action="click->lightbox#closeLightbox"
                aria-label="Close lightbox">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>

        <!-- Navigation Buttons -->
        <button class="lightbox-nav lightbox-prev" 
                data-lightbox-target="prev"
                data-action="click->lightbox#previousImage"
                aria-label="Previous image">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
          </svg>
        </button>

        <button class="lightbox-nav lightbox-next" 
                data-lightbox-target="next"
                data-action="click->lightbox#nextImage"
                aria-label="Next image">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
          </svg>
        </button>

        <!-- Main Image -->
        <div class="lightbox-content">
          <img data-lightbox-target="modalImage" 
               class="lightbox-image" 
               alt="Recipe image">
          
          <!-- Loading Spinner -->
          <div class="lightbox-spinner">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-white"></div>
          </div>
        </div>

        <!-- Image Counter -->
        <div class="lightbox-counter" data-lightbox-target="counter">
          1 / 1
        </div>

        <!-- View Original Link -->
        <div class="lightbox-original-link p-4">
          <a data-lightbox-target="originalLink" 
             href="#" 
             target="_blank" 
            class="text-white hover:text-gray-300 bg-black/50 hover:bg-black/75 px-6 py-2 rounded-full text-sm transition-all duration-200">
            <svg class="w-4 h-4 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"></path>
            </svg>
            View Original
          </a>
        </div>
      </div>
    </div>
  <% end %>


  <div class="bottomactions">
    <button class="button" data-action="click->recipe#favorite">
      <% if @recipe.favorite %> 
        <i class="fas fa-heart" data-recipe-target="favoriteicon"></i>
      <% else %>
        <i class="far fa-heart" data-recipe-target="favoriteicon"></i>
      <% end %>
    </button>
    <a  href="<%= edit_recipe_path @recipe %>">
      <button class="button">
        <i class="fas fa-edit"></i>
        <span><%=t 'action.edit' %></span>
      </button>
    </a>
    <button class="button" data-action="click->recipe#deleteShow">
      <i class="fas fa-trash"></i>
      <span><%=t 'action.delete' %></span>
    </button>

    <button class="button button-action hidden" data-action="click->recipe#delete" data-recipe-target="deleteButtons">
      <i class="fas fa-check"></i>
      <span><%=t 'yes' %></span>
    </button>

    <button class="button button-action hidden" data-action="click->recipe#deleteAbort" data-recipe-target="deleteButtons">
      <i class="fas fa-ban"></i>
      <span><%=t 'no' %></span>
    </button>

    <a href="<%= new_recipe_recipe_image_path @recipe %>">
      <button class="button">
        <i class="fas fa-camera"></i>
        <span><%=t 'action.image_add' %></span>
      </button>
    </a>
    <% if @recipe.recipe_images.count > 0 %>
      <a href="<%= delete_select_recipe_recipe_images_path @recipe %>" >
        <button class="button">
          <i class="fas fa-trash"></i>
          <span><%=t 'action.image_delete' %></span>
        </button>
      </a>
    <% end %>
    <% if @recipe.recipe_images.count > 0 %>
      <a href="<%= select_image_for_reparse_ocr_path @recipe %>" >
        <button class="button">
          <i class="fas fa-wand-magic-sparkles"></i>
          <span><%=t 'action.image_reparse' %></span>
        </button>
      </a>
    <% end %>
  </div>

  <div class="recipe_url mt-2">
    <span class="heading_3"><%=t 'url' %>:</span>
    <span><%= link_to recipe_url(@recipe) %></span>
  </div>
</div>