config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/health', to: 'health#liveness'
  get '/health/liveness', to: 'health#liveness'
  get '/health/readiness', to: 'health#readiness'

  get '/welcome', to: 'welcome#index'

  get '/profile', to: 'profile#index'
  get '/profile/change_password', to: 'profile#change_password', as: 'change_password'

  get '/auth/auth0/callback' => 'auth0#callback', as: 'auth0_callback'
  get '/auth/failure' => 'auth0#failure', as: 'auth0_failure'
  get '/auth/logout' => 'auth0#logout', as: 'auth0_logout'

  resources :recipes do
    collection do
      get 'filter_by_tag/:tagid' => :filter_by_tag, as: 'filter_by_tag'
      get 'search(/:term)' => :search, as: 'search'
      get 'new_magic' => :new_magic
    end
    member do
      put 'favorite'
    end
    resources :recipe_images, only: [:new, :create] do
      collection do
        get 'delete_select'
        put 'delete'
      end
    end
  end
  resources :tags do
    collection do
      get 'search(/:term)' => :search, as: 'search'
    end
  end

  resources :ocr, only: [] do
    collection do
      post 'scan'
      post 'select_recipe'
    end
    member do
      post 'cleanup_with_gpt'
      get 'select_image_for_reparse'
      post 'reparse_image'
      get 'select_recipe', to: 'ocr#show_recipe_selection', as: 'select_recipe'
    end
  end

  resources :ocr_debug, only: [:index, :show] do
    collection do
      post 'upload'
    end
  end

  root to: 'recipes#index'
end

app/controllers/recipe_images_controller.rb
require 'vips'

class RecipeImagesController < ApplicationController
  include Secured

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @page_title = @recipe.name
  end

  def create
    recipe = Recipe.find(params[:recipe_id])

    if params[:image].nil?
      flash[:error] = t('recipes.images.image_missing')
      redirect_to new_recipe_recipe_image_path(recipe) and return
    end

    params[:image].each{ |image|
      if image.content_type == "image/jpeg"
        # convert jpeg to webp using vips
        tmpfile = Tempfile.new('img', :encoding => 'ascii-8bit')
        im = Vips::Image.new_from_buffer image.read, ""
        im = im.autorot
        tmpfile.write(im.webpsave_buffer(Q: 60))
        tmpfile.close

        webp_filename = image.original_filename.sub(/\.jpg$/, '.webp').sub(/\.jpeg$/, '.webp')

        recipe.recipe_images.attach(
          io: tmpfile.open,
          filename: webp_filename,
          content_type: 'image/webp'
        )
        tmpfile.unlink
      else
        recipe.recipe_images.attach(image)
      end

    }

    recipe.save

    redirect_to recipe_path(recipe)
  end

  def delete_select
    @recipe = Recipe.find(params[:recipe_id])
    @page_title = @recipe.name
  end

  def delete
    filenames = params[:filenames].split ','
    logger.info filenames
    recipe = Recipe.find(params[:recipe_id])
    images_to_delete = recipe.recipe_images.select{ |i|
      filenames.include?(i.blob.filename.to_s)
    }
    images_to_delete.each{ |i|
      i.purge
    }

    redirect_to recipe_path(recipe)
  end
end

app/helpers/recipe_images_helper.rb
module RecipeImagesHelper
end

app/views/recipe_images/delete_select.html.erb
<div>
  <div class="mb-4">
    <span class="heading_2">
      <%=t 'action.image_delete' %> - <%=t @recipe.name %>
    </span>
  </div>
  <div class="delete_images" data-controller="recipeimagesdelete">
    <p>
      <%=t 'recipes.delete.info' %>
    </p>
    <div class="not-prose">
      <% @recipe.recipe_images.each do |image| %>
        <%= image_tag image.variant(resize_to_fit: [100,100]), 
                class: 'image_inline border-2 border-solid border-transparent', 
                data: { 
                  'filename': image.filename.to_s, 
                  action: 'click->recipeimagesdelete#select' 
                  } %>
      <% end %>
    </div>
    <%= form_tag(delete_recipe_recipe_images_path(@recipe), method: :put, data: { 'recipeimagesdelete-target': 'form'}) do %>
      <%= hidden_field_tag 'filenames', '', { 'data-recipeimagesdelete-target': 'filenames'} %>
      <div class="buttons mt-4">
        <span class="hidden" data-recipeimagesdelete-target="spinner">
            <i class="fas fa-2x fa-spinner fa-spin"></i>
        </span>
        <%= button_tag t('action.delete'), class: 'button', disabled: 'true', 
              'data-recipeimagesdelete-target': 'submitbutton', 'data-action': 'click->recipeimagesdelete#save' %>
        <a href="<%= recipe_path(@recipe) %>" class="not-prose">
          <%= button_tag t('action.cancel'), type: 'button', class: 'ml-4 button button-secondary' %>
        </a>
      </div>
    <% end %>
  </div
</div>

app/views/recipe_images/new.html.erb
<div class="container">
  <div class="mb-4">
    <span class="heading_2">
      <%=t 'action.image_add' %> - <%=t @recipe.name %>
    </span>
  </div>
  
  <div class="add_image" data-controller="recipeimagesadd">
    <%= form_tag(recipe_recipe_images_path(@recipe), method: :post, multipart: true, data: { 'recipeimagesadd-target': 'form'}) do %>
      <div data-recipeimagesadd-target="files">
        <div>
          <%= file_field_tag 'image[]', { accept: 'image/*', multiple: true, class: 'input', placeholder: t('recipes.form.placeholder.add_image') } %>
        </div>
        <div data-recipeimagesadd-target="buttons" class="mt-4">
          <span class="hidden" data-recipeimagesadd-target="spinner">
            <i class="fas fa-2x fa-spinner fa-spin"></i>
          </span>
          <%= button_tag t('action.save'), class: 'button', 
                data: { 
                  'action': 'click->recipeimagesadd#save', 
                  'recipeimagesadd-target': 'saveButton',
                  'alttext': t('action.saving'),
                } 
          %>
          <%= button_tag t('action.add_another'), type: 'button', class: 'button button-secondary', 'data-action': 'click->recipeimagesadd#add_another' %>
          <a href="<%= recipe_path(@recipe) %>" class="not-prose">
            <%= button_tag t('action.cancel'), type: 'button', class: 'button button-secondary' %>
          </a>
        </div>
      </div>
    <% end %>
    <div class="hidden"  data-recipeimagesadd-target="template">
      <%= file_field_tag 'image[]', { accept: 'image/*', multiple: true, class: 'input', placeholder: t('recipes.form.placeholder.add_image') } %>
    </div>
  </div>
</div>